import { Clip, Role } from "./types";
import { SAMPLE_CLIPS } from "./sampleClips";

export const ROLES: Role[] = [
  "drums",
  "bass",
  "chords",
  "texture",
  "vocal",
  "percussion",
  "noise",
  "fills",
];

export const ROLE_LABELS: Record<Role, string> = {
  drums: "Drums",
  bass: "Bass",
  chords: "Chords",
  texture: "Texture",
  vocal: "Vocal Dust",
  percussion: "Percussion",
  noise: "Noise",
  fills: "Fills",
};

const silence = (role: Role): Clip => ({
  id: `${role}-silence`,
  name: "Rest",
  role,
  kind: "silence",
  bars: 1,
  probability: 1,
  weirdness: 0,
  density: "low",
  moods: ["air"],
  returnToSilenceChance: 0,
  color: "#28313a",
});

export const DEFAULT_CLIPS: Clip[] = [
  ...ROLES.map(silence),
  ...SAMPLE_CLIPS,
  {
    id: "drums-dusty-pocket",
    name: "Dusty Pocket",
    role: "drums",
    kind: "pattern",
    bars: 2,
    probability: 0.9,
    weirdness: 0.18,
    density: "medium",
    moods: ["smoky", "steady"],
    returnToSilenceChance: 0.25,
    color: "#d56a44",
  },
  {
    id: "drums-ghost-step",
    name: "Ghost Step",
    role: "drums",
    kind: "pattern",
    bars: 1,
    probability: 0.65,
    weirdness: 0.28,
    density: "low",
    moods: ["sparse", "dusty"],
    returnToSilenceChance: 0.45,
    color: "#bc8257",
  },
  {
    id: "bass-window-rattle",
    name: "Window Rattle",
    role: "bass",
    kind: "pattern",
    bars: 2,
    probability: 0.78,
    weirdness: 0.22,
    density: "medium",
    moods: ["smoky", "heavy"],
    returnToSilenceChance: 0.32,
    color: "#609a7b",
  },
  {
    id: "chords-late-bus",
    name: "Late Bus",
    role: "chords",
    kind: "pattern",
    bars: 4,
    probability: 0.72,
    weirdness: 0.2,
    density: "medium",
    moods: ["pretty", "dim"],
    returnToSilenceChance: 0.42,
    color: "#c79a52",
  },
  {
    id: "texture-tape-room",
    name: "Tape Room",
    role: "texture",
    kind: "pattern",
    bars: 4,
    probability: 0.86,
    weirdness: 0.16,
    density: "low",
    moods: ["underwater", "hazy"],
    returnToSilenceChance: 0.28,
    color: "#6796b6",
  },
  {
    id: "vocal-window-phrase",
    name: "Window Phrase",
    role: "vocal",
    kind: "pattern",
    bars: 2,
    probability: 0.38,
    weirdness: 0.55,
    density: "high",
    moods: ["haunted", "rare"],
    returnToSilenceChance: 0.7,
    color: "#b96f8a",
  },
  {
    id: "percussion-matchbox",
    name: "Matchbox",
    role: "percussion",
    kind: "pattern",
    bars: 1,
    probability: 0.54,
    weirdness: 0.26,
    density: "high",
    moods: ["restless", "dry"],
    returnToSilenceChance: 0.55,
    color: "#a8a24f",
  },
  {
    id: "noise-bitcrush-door",
    name: "Bitcrush Door",
    role: "noise",
    kind: "pattern",
    bars: 1,
    probability: 0.22,
    weirdness: 0.9,
    density: "high",
    moods: ["broken", "collapse"],
    returnToSilenceChance: 0.82,
    color: "#8f80ba",
  },
  {
    id: "fills-stumble",
    name: "Stumble Fill",
    role: "fills",
    kind: "pattern",
    bars: 1,
    probability: 0.24,
    weirdness: 0.76,
    density: "high",
    moods: ["broken", "rare"],
    returnToSilenceChance: 0.9,
    color: "#cf5e67",
  },
];
